name: Build and Push Docker Image

on:
  push:
    branches:
      - master


permissions:
  contents: read
  packages: write

jobs:
  build-amd64:
    runs-on: ubuntu-latest

    steps:
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (AMD64)
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}:latest-amd
            ghcr.io/${{ env.REPO }}:${{ github.sha }}-amd
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-merge:
    runs-on: ubuntu-latest

    needs:
      - build-amd64

    steps:
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge
        run: |
          docker buildx imagetools create -t ghcr.io/${{ env.REPO }}:latest \
              ghcr.io/${{ env.REPO }}:latest-amd